### ISSUE TITLE
lxd: aarch64 build failure on Fedora >=33: libdqlite.so: undefined reference to `co_swap'

### ISSUE THREAD

**Issue by ganto** [ganto/copr-lxc4#5]
The LXD spec file for `>=lxd-4.3` fails to build on aarch64 for >=Fedora-33 (`1.15-1.fc33`/`1.15.1-1.fc34`). Unfortunately there is no clear build failure but it would always abort when trying to build `github.com/spf13/cobra/doc` as part of the `lxd` binary:
```
[...]
+ export GOPATH=/builddir/build/BUILD/lxd-4.5/_output:/builddir/build/BUILD/lxd-4.5:/usr/share/gocode
+ GOPATH=/builddir/build/BUILD/lxd-4.5/_output:/builddir/build/BUILD/lxd-4.5:/usr/share/gocode
+ unset LDFLAGS
+ export 'CGO_CFLAGS=-I/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/include/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/include/'
+ CGO_CFLAGS='-I/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/include/ -I/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/include/'
+ export 'CGO_LDFLAGS=-L/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs/ -Wl,-rpath,/usr/lib64/lxd'
+ CGO_LDFLAGS='-L/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs/ -Wl,-rpath,/usr/lib64/lxd'
+ export LD_LIBRARY_PATH=/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/.libs/:/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/:/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/.libs/:/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs/
+ LD_LIBRARY_PATH=/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/.libs/:/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/:/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/.libs/:/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs/
+ export CGO_LDFLAGS_ALLOW=-Wl,-wrap,pthread_create
+ CGO_LDFLAGS_ALLOW=-Wl,-wrap,pthread_create
+ for cmd in lxd lxc fuidshift lxd-benchmark lxc-to-lxd
+ BUILDTAGS=libsqlite3
++ head -c20 /dev/urandom
++ tr -d ' \n'
++ od -An -tx1
+ GOPATH=/builddir/build/BUILD/lxd-4.5/_build:/builddir/build/BUILD/lxd-4.5/_output:/builddir/build/BUILD/lxd-4.5:/usr/share/gocode:/usr/share/gocode
+ GO111MODULE=off
+ go build -buildmode pie -compiler gc '-tags=rpm_crashtraceback libsqlite3' -ldflags '-X github.com/lxc/lxd/version=4.5 -B 0xe952e8dee391a6b9b738499f509ecf65732698b2 -extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '\''' -a -v -x -o /builddir/build/BUILD/lxd-4.5/_build/bin/lxd github.com/lxc/lxd/lxd

[...]

cd /builddir/build/BUILD/lxd-4.5/_build/src/github.com/lxc/lxd/vendor/github.com/spf13/cobra/doc
/usr/lib/golang/pkg/tool/linux_arm64/compile -o $WORK/b350/_pkg_.a -trimpath "$WORK/b350=>" -shared -p github.com/lxc/lxd/vendor/github.com/spf13/cobra/doc -complete -installsuffix shared -buildid F7yqV7gz_lrMzjFqiaJP/F7yqV7gz_lrMzjFqiaJP -goversion go1.15.1 -D "" -importcfg $WORK/b350/importcfg -pack ./man_docs.go ./md_docs.go ./rest_docs.go ./util.go ./yaml_docs.go
/usr/lib/golang/pkg/tool/linux_arm64/buildid -w $WORK/b350/_pkg_.a # internal
cp $WORK/b350/_pkg_.a /builddir/.cache/go-build/1d/1d36b0fc73b949a1f633a60f9387540ab92dfb6cc7c7f33d8a652b1f09129d0a-d # internal
/usr/lib/golang/pkg/tool/linux_arm64/buildid -w $WORK/b340/_pkg_.a # internal
cp $WORK/b340/_pkg_.a /builddir/.cache/go-build/68/681f9b0f83ad667bfc9540eae69b97342491eb8631e716e0483032aa467d9f28-d # internal
error: Bad exit status from /var/tmp/rpm-tmp.cC1Udw (%build)
    Setting %{thisgofilelist} = devel.file-list
    Setting %{currentgoipath} = github.com/lxc/lxd
    Setting %{currentgosourcedir} = /builddir/build/BUILD/lxd-4.5
    Setting %{currentgofilelist} = devel.file-list
    Setting %{currentversion} = 4.5
    Setting %{currentgoldflags} =  -X github.com/lxc/lxd/version=4.5
    Bad exit status from /var/tmp/rpm-tmp.cC1Udw (%build)
```

See e.g. ganto/lxc4: [COPR build 01652912 - build.log.gz](https://download.copr.fedorainfracloud.org/results/ganto/lxc4/fedora-rawhide-aarch64/01652912-lxd/build.log.gz)

On Fedora 31/32 (using `1.13.14-1.fc31` and `golang-1.14.7-1.fc32`) the aarch64 build is successful.

**Comment by ganto** [comment]
After a closer look I found:
```
TERM='dumb' gcc -I . -fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b187=/tmp/go-build -gno-record-gcc-switches -o $WORK/b187/_cgo_.o $WORK/b187/_cgo_main.o $WORK/b187/_x001.o $WORK/b187/_x002.o $WORK/b187/_x003.o -L/builddir/build/BUILD/lxd-4.5/_dist/deps/sqlite/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/libco/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/raft/.libs/ -L/builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs/ -Wl,-rpath,/usr/lib64/lxd -lsqlite3 -lraft -lco -ldqlite
# github.com/lxc/lxd/vendor/github.com/canonical/go-dqlite/internal/bindings
/usr/bin/ld: /builddir/build/BUILD/lxd-4.5/_dist/deps/dqlite/.libs//libdqlite.so: undefined reference to `co_swap'
collect2: error: ld returned 1 exit status
```
I guess it's the same root cause as #6

**Comment by ganto** [comment]
Fixed in `lxd-4.5-0.2`
